config/routes.rb
Rails.application.routes.draw do
 get "/home" => "pages#home"
 
 root "pages#home"
 
 #this gets the following
 #index / #show
 #edit / #update
 #new / #create
 #destroy
 
 resources :recipes do
 
  member do
    post "like"
    post "comment"
    patch "changevote"
  end
 
 end
 
 resources :comments, only: [:destroy]
 
 resources :chefs, except: [:new]
 
 get '/register', to: 'chefs#new'
 
 #login and logout
 
 get '/login', to: 'logins#new'
 post '/login', to: 'logins#create'
 get '/logout', to: 'logins#destroy'
 
 resources :styles, only: [:new, :create, :show]
 resources :ingredients, only: [:new, :create, :show]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes, dependent: :destroy
    
    has_many :comments, dependent: :destroy
    
    has_many :recipe_styles, dependent: :destroy
    has_many :styles, through: :recipe_styles
    
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients
    
    validates :chef_id,     presence: true 
    validates :name,        presence: true, length: { in: 2..30 }
    validates :summary,     presence: true, length: { in: 5..100 }
    validates :description, presence: true, length: { in: 5..300 }
    #this was added to allow for pictures after installing gem and adding
    #picture field to recipes -> gem was carrierwave
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    default_scope -> { order(created_at: :desc) }
    
    def thumbs_up_total
       self.likes.where(like: true).size 
    end
    
    def thumbs_down_total
       self.likes.where(like: false).size 
    end
    
    def chef_comments(c)
       self.comments.where(chef: c)
    end
    
    def chef_likes(c)
        self.likes.where(chef: c)
    end
    
    private
    
    def picture_size
       if picture.size > 5.megabytes
           errors.add(:picture, "should be less than 5 mb")
       end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   
   before_action :set_recipe, only: [:show, :edit, :update, :like, :destroy, :comment, :changevote]
   before_action :require_user, except: [:show, :index]
   before_action :require_same_user, only: [:edit, :update]
   
   def index
       @recipes = Recipe.paginate(page: params[:page], per_page: 3)
   end
   
   def show
     @comments = @recipe.comments
   end
   
   def destroy
      @recipe.destroy
      flash[:success] = "Recipe deleted"
      redirect_to recipes_path
   end   
   
   def new
      @recipe = Recipe.new
   end
   
   def edit
       
   end
   
   def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef=current_user
      
      if @recipe.save
         flash[:success] = "Your new recipe was added"
         redirect_to @recipe
      else
        flash[:danger] = @recipe.errors.full_messages
        render :new
      end
   end
   
   def update
      if @recipe.update(recipe_params)
         flash[:success] = "Recipe Updated"
         redirect_to recipe_path(@recipe)
      else
        flash[:danger] = @recipe.errors.full_messages
        render :new
      end
   end
   
   def comment
      comment = Comment.create(content: params[:content], chef: current_user, recipe: @recipe)
      if comment.valid?
         flash[:success] = "Your comment was recorded."
      else
         flash[:danger] = "You can only comment once for each recipe."
      end
      redirect_to :back
   end
   
   
   def like
         like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
         if like.valid?
            flash[:success] = "Your vote for " + @recipe.name + " was recorded."
         else
            flash[:danger] = "You can only vote once for each recipe."
         end
      redirect_to :back
   end
   
   def changevote
      like=Like.where(recipe: @recipe, chef: current_user).first
      like.toggle!(:like)
      flash[:success] = "Your vote for " + @recipe.name + " has been changed."
      redirect_to :back
   end
   
   private #----------------------
   
   def recipe_params
         params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
   end
   
   def set_recipe
       @recipe = Recipe.find(params[:id])
   end
   
   def require_same_user
       if !current_user.admin && current_user != @recipe.chef
          flash["danger"] = 'You can only edit your own recipes '
          redirect_to recipes_path
       end
   end
   
end

app/views/recipes/_form.html.erb
<div class="row">
    <div class='col-md-8 col-md-offset-2 well'>
        <%= form_for(@recipe, html: { multipart: true }) do |f| %>
            <div class="form-group">
              Recipe Name: <%= f.text_field :name, class:"form-control" %><br />
            </div>
            
            <div class = "form-group">
              Summary : <%= f.text_field :summary, class:"form-control" %><br />
            </div>
            
            <div class = "form-group">
              Description : <%= f.text_area :description, :rows => "8", class:"form-control" %><br />
            </div>
             <div class = "form-group">
           Styles (check all that apply):<br/>
            
            <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline") { cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
            </div>
             <div class = "form-group">
            Ingredients (check all that apply):<br/>
            
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline") { cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
            </div>
            
            
              Upload Image: <i>(optional)</i>
               <%= f.file_field :picture, accept:'image/jpeg,image/gif,image/png' %><br />
  
              <%= f.submit @recipe.new_record? ? "Create Recipe" : "Update Recipe", class:"btn btn-warning" %>
              <%= link_to "Cancel", :back, class:"btn btn-danger" %>
        <% end %>
    </div>
</div>

app/views/recipes/edit.html.erb
<H1>Edit Recipe</H1><hr/>
<%= render 'form' %>

app/views/recipes/index.html.erb
<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
        <%= link_to "Chefs", chefs_path %>
    </li>
</ul>

<table width=100%>
    <tr>
        <td width=60%>
             <h1 style="text-align: right;">View All Recipes</h1>
        </td>
        <td> <span class="pull-right"><%= will_paginate %></span> </td>
    </tr>
</table><hr/>
    

<% @recipes.each do |r| %>
<div class="row">
    <div class = "col-md-2 imgspace">
        <%= get_gravimage r.chef, size:100  %>
        <br/>
       <small> Posted by:
        <%= link_to r.chef.chefname, r.chef %> </small>
    </div>
        <div class = "col-md-6 well">
           <h3 style='margin-top: -5px'><%= link_to r.name, r %> </h3><br>
            <p> <%= r.summary %></p>
            
               <% if r.styles.any? %>
                <p> Styles: <% r.styles.each do |style| %>
                    | <%= link_to style.name, style %>
                <% end %>
                </p>
            <% else %>
                <p>Styles: | n/a</p>
            <% end %>
            <% if r.ingredients.any? %>
                <p> Ingredietns: <% r.ingredients.each do |ing| %>
                    | <%= link_to ing.name, ing %> 
                <% end %>
                </p>
            <% else %>
                <p>Ingredients: | n/a</p>
            <% end %>
        
            
            <small>Posted <%= time_ago_in_words(r.created_at) %> ago.</small>
            
              <div class="pull-right">
                <% if logged_in? %>
                    <% if r.chef_likes(current_user).size==1 %>
                    <% cheflike = r.chef_likes(current_user).first %>
                        <small>You have <b><%= (cheflike.like == true ? "liked" : "disliked") %></b> this recipe. 
                        [<%= link_to changevote_recipe_path(r), method: :patch do %> Change your vote <% end %>]</small><br>
                    <% else %>
                        <small>You have not yet voted for this recipe</small><br>
                    <% end %>
                <% end %>
                <small><%= r.thumbs_up_total %></small>
                <%= link_to like_recipe_path(r, like: true), method: :post do %>
                    <span class="glyphicon glyphicon-thumbs-up"></span> <small>Like</small>
                <% end %> | 
                <small><%= r.thumbs_down_total %></small>
                 <%= link_to like_recipe_path(r, like: false), method: :post do %>            
                <span class="glyphicon glyphicon-thumbs-down"></span> <small>Dislike</small> 
                <% end %>
            </div>
        </div>
        <div class = "col-md-3">
            <%= image_tag(r.picture.url, size: "200x100", class: "imgspace img-thumbnail") if r.picture? %>
        </div>
    </div>
    <hr/>
<% end %>
<div style="margin-top:-40px;">
<%= will_paginate %>    
</div>

app/views/recipes/new.html.erb
<H1>Add a Recipe</H1><hr/>
<%= render 'form' %>

app/views/recipes/show.html.erb
<ul class="nav nav-tabs">
    <li>
        <%= link_to "Back to All Recipes", recipes_path %>
    </li>
</ul>

<h1><%= @recipe.name %> Details</h1>

<div class="row">
    <div class="col-md-2 imgspace">
        <small>Brought to you by</small><br/>
        <%= get_gravimage @recipe.chef, size:150  %> <br/>
       <%= link_to @recipe.chef.chefname, @recipe.chef %> 
       
    </div>
    <div class="col-md-9 well">
    <div class="row">
        <div class="col-md-7">
            <h3>Summary:  <%= @recipe.summary %> </h3><hr style = 'background-color: #999; height: 2px' />
            <%= simple_format(@recipe.description) %>
            
            <% if @recipe.styles.any? %>
                <p> Styles: <% @recipe.styles.each do |style| %>
                    | <%= link_to style.name, style %>
                <% end %>
                </p>
            <% else %>
                <p>Styles: | n/a</p>
            <% end %>
            <% if @recipe.ingredients.any? %>
                <p> Ingredietns: <% @recipe.ingredients.each do |ing| %>
                    | <%= link_to ing.name, ing %> 
                <% end %>
                </p>
            <% else %>
                <p>Ingredients: | n/a </p>
            <% end %>
        <% if @recipe.chef == current_user || (logged_in? && current_user.admin) %>
        <br/><br/>
           <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-warning btn-sm" %>
           <%= link_to "Delete Recipe", @recipe, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
            
        <% end %>
        </div>
        
        <div class="col-md-5">
            <%= image_tag(@recipe.picture.url, size:"400x240", class: 'img img-rounded img-responsive') if @recipe.picture? %> <br/>
            <div class="pull-right">
                <% if logged_in? %>
                    <% if @recipe.chef_likes(current_user).size==1 %>
                    <% cheflike = @recipe.chef_likes(current_user).first %>
                        <small>You have <b><%= (cheflike.like == true ? "liked" : "disliked") %></b> this recipe. 
                        [<%= link_to changevote_recipe_path, method: :patch do %> Change your vote <% end %>]</small><br>
                    <% else %>
                        <small>You have not yet voted for this recipe</small><br>
                    <% end %>
                <% end %>
                <small><%= @recipe.thumbs_up_total %></small>
                <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                    <span class="glyphicon glyphicon-thumbs-up"></span> <small>Like</small>
                <% end %> | 
                <small><%= @recipe.thumbs_down_total %></small>
                 <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>            
                <span class="glyphicon glyphicon-thumbs-down"></span> <small>Dislike</small> 
                <% end %>
            </div>
        </div>
    </div>
    </div>  
</div>
<div class="row">
    <div class="col-md-9 col-md-offset-2">
        
        <div id="comform">
        
        <h5 style="margin-top: 0px;">Leave a Comment  <button id="btncancel" class="btn btn-danger btn-xs">Cancel</button> </h5>
            <%= form_tag(comment_recipe_path, :method=>'post') do %>
                <div class="form-group">
                    <%= text_area_tag 'content', nil, rows:5, cols: 40, class:"form-control" %><br />
                </div>
            <%= submit_tag "Submit Comment", class: "btn btn-primary" %> 
             <% end %>
           
        </div>
        
        <% if logged_in? %>
            <% if @recipe.chef_comments(current_user).size==1 %>
                <% chefcom = @recipe.chef_comments(current_user).first %>
               
                <p class="well"><b>You have commented: &nbsp;&nbsp;&nbsp;</b> <%= @recipe.chef_comments(current_user).first.content %> 
                | <%= link_to "Delete comment", comment_path(chefcom), method: :delete %> </p>
                
            <% else %>
                <button id="btncom" class="btn btn-primary">Leave a comment</button>
            <% end %>
        <% else %>
             <h5 style="margin-top: 0px;"> <%= link_to "Log in ", login_path %> to leave a Comment</h5>
        <% end %>
    </div>
</div>
<div class="row">
     <div class="col-md-9 col-md-offset-2">
    <h2>All Comments</h2>
    <table width=100%>
    <th>Posted By</th><th>Comment</th>
    <% @comments.each do |com| %>
    <tr class="well">
        <td width=20%>
            <div class="pull-left">
                <%= get_gravimage(com.chef, size:50) %>
            </div>
            <div style="width:50px;padding-top:10px;padding-left:10px;float:left;">
                <small><%= com.chef.chefname %> </small>
            </div>
        </td>
        <td class="comment">
            <%= com.content %>
            <br><small><i><%= com.updated_at.strftime("%m/%d/%Y") %></i></small>
        </td>
    </tr>
    <% end %>
    </table>
    </div>
</div>

<script type = "text/javascript">

  $('document').ready(function() {
    $("#comform").hide();  
   $("#btncom").click(function(){ 
    $("#comform").slideDown("fast");  
     $("#btncom").hide();
   });
   $("#btncancel").click(function(){ 
    $("#comform").hide();  
     $("#btncom").show();
   });
});
  
 
</script>