config/routes.rb
Rails.application.routes.draw do
 get "/home" => "pages#home"
 
 root "pages#home"
 
 #this gets the following
 #index / #show
 #edit / #update
 #new / #create
 #destroy
 
 resources :recipes do
 
  member do
    post "like"
    post "comment"
    patch "changevote"
  end
 
 end
 
 resources :comments, only: [:destroy]
 
 resources :chefs, except: [:new]
 
 get '/register', to: 'chefs#new'
 
 #login and logout
 
 get '/login', to: 'logins#new'
 post '/login', to: 'logins#create'
 get '/logout', to: 'logins#destroy'
 
 resources :styles, only: [:new, :create, :show]
 resources :ingredients, only: [:new, :create, :show]
end

app/views/pages/home.html.erb
<div class="jumbotron center">
    <div class="jumbotext">
    <h1>Welcome to Cookera App</h1>
     <p>A place to share your favourite recipes</p><br/>
    <%= link_to "Sign up now", register_path, class: "btn btn-lg btn-primary" %>
    <br/>&nbsp;
    </div>
</div>

<div class="container">
<div class="row">
    <div class="col-lg-6">
        <h3 class="midrow">
            View Recipes as Guest User
        </h3>
        <h2 class="left">Browse and view all recipes as a guest and Sign up later.  You can also filter by styles or ingredients.</h2>
        <p> <%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %> </p>
    </div>

    <div class="col-lg-6">
        <h3 class="midrow">
            Log Into Cookera as a Chef
        </h3>
        <h2 class="left">Log in to add new recipes, edit your own recipes, vote on recipies and more!</h2>
        <% if logged_in? %>
            <p class="left" style="background: #f8f4e3;padding:10px;">You are already logged in as: <%= current_user.chefname %> </p>
        <% else %>
            <p> <%= link_to "Log Into Cookera", login_path, class: "btn btn-warning btn-small" %> </p>
        <% end %>
    </div>
</div>
  <div class='footer'>
    <p>&copy; Cookera 2015 by Tony Gu</p>
  </div>
</div>