config/routes.rb
Rails.application.routes.draw do
 get "/home" => "pages#home"
 
 root "pages#home"
 
 #this gets the following
 #index / #show
 #edit / #update
 #new / #create
 #destroy
 
 resources :recipes do
 
  member do
    post "like"
    post "comment"
    patch "changevote"
  end
 
 end
 
 resources :comments, only: [:destroy]
 
 resources :chefs, except: [:new]
 
 get '/register', to: 'chefs#new'
 
 #login and logout
 
 get '/login', to: 'logins#new'
 post '/login', to: 'logins#create'
 get '/logout', to: 'logins#destroy'
 
 resources :styles, only: [:new, :create, :show]
 resources :ingredients, only: [:new, :create, :show]
end

app/views/layouts/_footer.html.erb
<div class='footer'>
  <p>&copy; Cookera 2015 by Tony Gu</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <% flash.each do |msgtype, msg| %>
        <div class="alert alert-<%= msgtype %>">
                <%= msg %>
                <a class="close" data-dismiss="alert">x</a>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-default">

    <div class="container">

      <% if logged_in? %>
        <%= link_to "Cookera Home", recipes_path, class: "btn btn-lg btn-success", id: "logo" %>
      <% else %>
         <%= link_to "Cookera Home", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <% end %>

       <div class="topmen">
             <ul class="dropdown">
              <%= link_to "#", class: "btn btn-warning dropdown-toggle", "data-toggle" => "dropdown" do %>
                Browse By Style <b class="caret"></b>
                <% end %>
                <ul class="dropdown-menu">
                    <% Style.all.each do |style| %>
                      <li> <%= link_to style.name, style %></li>
                    <% end %>

                    <% if logged_in? %>
                     <li class="divider"></li>
                     <li> <%= link_to "Add a New Style", new_style_path %> </li>
                    <% end %>
                </ul>
            </ul>
      </div>

       <div class="topmen">
             <ul class="dropdown">
              <%= link_to "#", class: "btn btn-warning dropdown-toggle", "data-toggle" => "dropdown" do %>
               Browse By Ingredient <b class="caret"></b>
                <% end %>
                <ul class="dropdown-menu">
                    <% Ingredient.all.each do |ing| %>
                      <li> <%= link_to ing.name, ing %></li>
                    <% end %>
                     <% if logged_in? %>
                     <li class="divider"></li>
                     <li> <%= link_to "Add a New Ingredient", new_ingredient_path %> </li>
                    <% end %>
                </ul>
            </ul>
      </div>



      <% if logged_in? %>
          <div class="topmen" style="margin-left: 25px;">
            <%= link_to "Add a New Recipe", new_recipe_path, class: "btn btn-warning" %>
          </div>

          <!--dropdown -->
          <div style="float:right">
          <ul class="topmen" style="margin-right:5px;border-left: 1px solid white">
            <li class="dropdown">
              <%= link_to "#", class: "btn btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
                User Options <b class="caret"></b>
                <% end %>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Profile", chef_path(current_user) %></li>
                  <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
                  <li class="divider"></li>
                  <li> <%= link_to "Logout", logout_path %> </li>
                </ul>
            </li>
          </ul>
         <div class='pull-right'>
             <div class="pull-left">
                <%= get_gravimage(current_user, size:50) %>
            </div>
            <div style="width:150px;padding-top:10px;padding-left:10px;float:left;">
                <small style="color:white;">Logged in as:<br/> <%= current_user.chefname %> </small>
            </div>

         </div>

      <% else %>
            <div class="topmen pull-right">
            <%= link_to "Login", login_path, class: "btn btn-warning" %>
          </div>
      <% end %>


    </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookera Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Signika:400,600,300,700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>
  <% if current_page?(root_path) %>
    <%= yield %>
  <% else %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <% end %>
</body>
</html>